import { z } from "zod";

export const InsertEmployeeContractSchema = z.object({
  id: z.string().uuid().optional(), // generated by default
  userId: z.string().uuid(),
  status: z.string().default("new"),
  contract_name: z.string(),
  start_date: z.coerce.date(), 
  end_date: z.coerce.date(),
  working_schedule: z.string(),
  job_position: z.string(),
  wage_on_signed: z.number().default(0),
  contract_type: z.string(),
  salary_structure_type: z.string(),
  hr_responsible: z.string(),
  department_id: z.string().uuid().nullable().optional(), 
  employee_id: z.string().uuid(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional()
});
