
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/Header";
import { TRPCProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import SessionWrapper from "@/components/auth/SessionWrapper";
import { getQueryClient, trpc } from "@/trpc/server";
// import Provider from "@/components/auth/Provider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const queryClient = getQueryClient()
  void queryClient.prefetchQuery(trpc.getUser.getMe.queryOptions())

  return (
    <html lang="en">
      <body
        className={`${inter.className}  h-screen overflow-hidden`}
      >
    <TRPCProvider>
    <SessionWrapper>
        <Header/>
        {children}
        <Toaster/>
    </SessionWrapper>
    </TRPCProvider>
    </body>
    </html>
  );
}
